### ISSUE TITLE
When destroying a service instance, the service instance gets unbound from the app, yet the database doesn't seem to be removed.

### ISSUE THREAD

**Issue by dhilton** [tsuru/postgres-api#9] opened 2015-06-11 09:36 UTC
(This maybe related to https://github.com/tsuru/postgres-api/issues/8)

To replicate:
1. Create a new instance of a postgresql service to add to an app. "pTest1"
2. Try and destroy that instance.
3. Try and create a new DB instance with the same name.
4. If you try to create service with the same name again, you get Error: Failed to create the instance pTest1: Instance pTest1 already exists.

This maybe related to the uppercase issue however, be good to have a regression test in the test suite to check / remove this issue.

**Comment by sroze** [comment] 2015-07-23 20:37
This is fixed by #12, as it's a duplicate of #1.

**Closed as completed by sroze** 2015-07-23 20:37 UTC
